console.log('hello, world');
const h1Elem = document.querySelector('h1');
console.log('h1 element:', h1Elem);
console.dir(h1Elem);
const idExplaination = document.querySelector('#explanation');
console.log('id explanation:', idExplaination);
console.dir(idExplaination);
const classHint = document.querySelector('.hint');
console.log('class hint:', classHint);
console.dir(classHint);
const para = document.querySelectorAll('p');
console.log('paragrah:', para);
const allClass = document.querySelectorAll('.example-link');
console.log('links:', allClass);
