var fullName = 'Nang Tu';
var isCool = true;
var totalPets = 0;
var unknown = null;
var never = undefined;
console.log('value of fullName:', fullName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('typeOf fullName:', typeof fullName);
console.log('typeOf isCool:', typeof isCool);
console.log('typeOf totalPets:', typeof totalPets);
console.log('value of unknown:', unknown);
console.log('typeOf unknown:', typeof unknown);
console.log('value of never:', never);
console.log('typeOf never:', typeof never);
