var width = 20;
var height = 11;
var area = width * height;
console.log('value of area:', area);
console.log('typeOf area:', typeof area);
var bill = 13.99;
var payment = 20;
var change = payment - bill;
console.log('value of change:', change);
console.log('typeOf change:', typeof change);
var quizzes = 30;
var midterm = 32;
var final = 99;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeOf grade:', typeof grade);
var firstName = 'Leon';
var lastName = 'Kennedy';
var fullName = ''.concat(firstName, ' ').concat(lastName);
console.log('value of fullName:', fullName);
console.log('typeOf fullName:', typeof fullName);
var pH = 6;
var isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeOf isAcidic:', typeof isAcidic);
var headCount = 300;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeOf isSparta:', typeof isSparta);
var motto = ''.concat(fullName, ' is the GOAT');
console.log('value of motto:', motto);
console.log('typeOf motto:', typeof motto);
